### ISSUE TITLE
Setting page is empty

### ISSUE THREAD

**Issue by ugintl** [singularo/stratoserp_base#11] opened 2021-05-23 15:41 UTC
When I go to settings page, it shows like this. Is it normal?
![erp-settings](https://user-images.githubusercontent.com/12570802/119267259-2ebf1600-bc07-11eb-9001-b2218f1cde70.png)

**Comment by singularo** [comment] 2021-07-11 07:29
There just isn't anything there to configure at the moment. Some of the other entities do have settings.
This is currently the expected behaviour, so not really a bug/issue.

**Comment by singularo** [comment] 2022-04-18 03:13
Lots of changes since this. Some entities still do not have any actual settings, others do.
Closing this as expected behaviour for now.

**Closed as completed by singularo** 2022-04-18 03:13 UTC
